### ISSUE TITLE
julian_day in tide_tools.py

### ISSUE THREAD

**Issue by huangqingze** [pwcazenave/PyFVCOM#2]
The function julian_day in tide_tools.py, when  calculate Julian Day , such as:
julian, modified = jdcal.gcal2jd(year, month, day)
julian += (hour + (minute / 60.0) + (second / 3600.0)) / 24.0
modified += (hour + (minute / 60.0) + (second / 3600.0)) / 24.0
the first output of jdcal.gcal2jd: julian is  equal to MJD_0=2451545.5,the second output of jdcal.gcal2jd: modified is MJD, and if want to return Julian Day ,we must add the julian and modified together.
So when the function calculate Julian Day just use the julian is wrong. I think it would like this:
julian, modified = jdcal.gcal2jd(year, month, day)
modified += (hour + (minute / 60.0) + (second / 3600.0)) / 24.0
julian+=modified

**Comment by pwcazenave** [comment]
Thanks for the report - I've fixed this in the dev branch.

**Comment by pwcazenave** [comment]
Fixed in 56e071adbb3d5fdd74bbc36dea88cfcc831e761e.
