### ISSUE TITLE
Possible bug in Plotter function.

### ISSUE THREAD

**Issue by mugun33** [pwcazenave/PyFVCOM#3]
Hello,

When I provide the "extents" input to the Plotter function, it did NOT produce the **axes labels.**
You can find an example of command below;
Best Regards,
Murat

plot = Plotter(fvcom,
               figsize=(20, 20),
               res='f',
               vmin=28,
               **extents=[26.35,27.2,38.25,38.8],**
               vmax=39.3,
               tick_inc=(4, 2),
               cb_label='{} ({})'.format(fvcom.atts.salinity.long_name,
                                         fvcom.atts.salinity.units),
               cmap=cm.haline)

**Comment by pwcazenave** [comment]
The values you've passed with tick_inc (in units of degrees) are too large
for the extents you've given.

Pierre

**Comment by mugun33** [comment]
Yes! Thank you very much.
