### ISSUE TITLE
the issue about add_tpxo_tides

### ISSUE THREAD

**Issue by stqiuzhou** [pwcazenave/PyFVCOM#4]
when I run the function 'add_tpxo_tides' , some trouble showed:
D:\software\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py:2530: RuntimeWarning: invalid value encountered in true_divide
  (grid[i + 1] - grid[i]))
D:\software\Anaconda3\lib\site-packages\utide\_reconstruct.py:106: RuntimeWarning: invalid value encountered in greater_equal
  ind = np.logical_and(SNR >= min_SNR, PE >= min_PE)

so I can not wirter tides to nc file

**Comment by pwcazenave** [comment]
The only thing I can think of is that I've found that the linear interpolation method used by `add_tpxo_tides` can induce weird behaviour along an open boundary. I'm currently investigating why that is and trying to see if I can fix it. 

At the moment, I get more sensible open boundary tide distributions by using the 'nearest' method on `RegularGridInterpolator`, but this produces steps in the interpolated solution, which means it needs to be smoothed afterwards (which I haven't implemented yet).

If you are able to, it would be interesting to know what the values of the TPXO amplitudes and phases are at the positions of your open boundaries. You should be able to extract those by editing the function `_interpolate_tpxo_harmonics` around line 1206 in `grid.py` to output to a couple of files:

```python
        np.savetxt('amplitudes.txt', amp_data, fmt='%.6f')
        np.savetxt('phases.txt', phase_data, fmt='%.6f')
```
Alternatively, if you don't mind sharing your grid, I can try to replicate the behaviour to see if I can fix it (this would be a lot quicker for me!).

**Comment by stqiuzhou** [comment]
The attachment is my grid file.
my OS：window 10
My python code :

from datetime import datetime
import PyFVCOM as pf

# path to 2dm
sms_file = r'D:\2018_2019_research\china_sea_1993\fvcom_input_file\sms.2dm'
# define time
start = datetime.strptime('1993-08-01', '%Y-%m-%d')
end = datetime.strptime('1993-11-01', '%Y-%m-%d')
interval = 1 / 24
model = pf.preproc.Model(start, end, sms_file, sampling=interval,
                         native_coordinates='spherical', zone='20N')

# tide
tpxo_harmonics =
r'D:\2018_2019_research\china_sea_1993\tpxo9_netcdf\h_tpxo9.v1.nc'
# constituents = ['M2', 'S2', 'N2', 'K2', 'K1', 'O1', 'P1', 'Q1']
constituents = ['M2']
for boundary in model.open_boundaries:
    boundary.add_sponge_layer(5000, 0.001)
    boundary.add_type(1)
    boundary.add_tpxo_tides(tpxo_harmonics, predict='zeta',
constituents=constituents, interval=interval)

thank you very much！



Pierre Cazenave <notifications@github.com> 于2019年1月21日周一 下午5:46写道：

**Comment by pwcazenave** [comment]
Apologies for not getting back to you sooner. I'm afraid I didn't receive the grid attachment - could you send it to me via my PML email address: \<removed\>

**Comment by pwcazenave** [comment]
Thank you for sending the file. 

I've tested the code you posted above with the SMS grid you sent me with both the current `master` and `dev` branches. I am able to reproduce the error you get when using `master`, so there's obviously some bug in there somewhere. However, I can successfully generate boundary forcing using the `dev` branch:

![figure_1](https://user-images.githubusercontent.com/531784/52941646-37a64a80-3361-11e9-9c45-63aaa4f504d3.png)

If you are able, you can update to the latest version of the `dev` branch by either downloading and installing the archive or checking out the `dev` branch from `git`.

**Comment by stqiuzhou** [comment]
thank you very much. I will try it .

Pierre Cazenave <notifications@github.com> 于2019年2月18日周一 下午5:41写道：

**Comment by pwcazenave** [comment]
Did you manage to get this working?
