### ISSUE TITLE
ModuleNotFoundError: No module named 'cartopy'

### ISSUE THREAD

**Issue by AllOtherUserNamesTaken** [pwcazenave/PyFVCOM#6]
Hi to whom it may concern, 

cartopy is missing from the setup.py install_requires. See below:

Matplotlib is building the font cache; this may take a moment.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9e3122ff6756> in <module>()
----> 1 from PyFVCOM.read import FileReader

...\lib\site-packages\PyFVCOM\__init__.py in <module>()
     23 from PyFVCOM import tidal_ellipse
     24 from PyFVCOM import tide
---> 25 from PyFVCOM import plot
     26 from PyFVCOM import preproc
     27 from PyFVCOM import read

...\lib\site-packages\PyFVCOM\plot.py in <module>()
      7 from pathlib import Path
      8 
----> 9 import cartopy.crs as ccrs
     10 import cartopy.feature as cfeature
     11 import matplotlib.widgets

ModuleNotFoundError: No module named 'cartopy'
​

**Comment by pwcazenave** [comment]
Hi,

Sorry for the late reply. I'm not actively working on PyFVCOM any more (change of career). However, the guys at PML are and you should be able to see the latest release of the code there:

https://gitlab.ecosystem-modelling.pml.ac.uk/fvcom/pyfvcom

**Comment by q1165600785** [comment]
Hello author, what is your current job? I'm not sure if you've seen this message, but I would like to use pyfvcom

**Comment by q1165600785** [comment]
Hello author, what is your current job? I'm not sure if you've seen this message, but I would like to use pyfvcom

**Comment by pwcazenave** [comment]
This is resolved in the PML copy of this module: https://github.com/pmlmodelling/pyfvcom
